name: Test

on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        go: [1.17.x]
    name: '${{ matrix.platform }} | ${{ matrix.go }}'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Unit testing
        run: |
          make coverage-check
